# Allow compute credits usage by collaborators and bors.
use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying'

# Use an expired token that was used when fixtures were generated.
env:
  INQ_GITHUB_USERNAME: "duckinator"
  INQ_GITHUB_TOKEN: "9182777ff3c006795193a570cdac326b64459dc9"
  INQ_USE_ENV: "true"

Lint_task:
  container:
    image: ruby:2.7-alpine
  install_script:
    - apk add --no-cache git build-base
    - gem install bundler
    - bundle install
  script:
    - ruby --version
    - bundle exec rubocop

Linux_task:
  container:
    matrix:
      - image: ruby:2.5-alpine
      - image: ruby:2.6-alpine
      - image: ruby:2.7-alpine
  install_script:
    - apk add --no-cache git build-base
    - gem install bundler
    - bundle install
  script:
    - ruby --version
    - bundle exec rake spec

macOS_task:
  osx_instance:
    image: mojave-base
  env:
    matrix:
      - RUBY_VERSION: 2.5
      - RUBY_VERSION: 2.6
      - RUBY_VERSION: 2.7
    PATH: "/usr/local/opt/ruby@${RUBY_VERSION}/bin:$HOME/.gem/ruby/${RUBY_VERSION}.0/bin:$PATH"
  install_script:
    - "brew install ruby@${RUBY_VERSION}"
    - gem install bundler --user-install
    - bundle install
  script:
    - ruby --version
    - bundle exec rake spec

# NOTE: The `ruby` package on FreeBSD 12.1 is currently Ruby 2.6.
FreeBSD_task:
  freebsd_instance:
    image_family: freebsd-12-1
  env:
    RUBY_VERSION: 2.6
  install_script:
    - RB=`echo $RUBY_VERSION | tr -d '.'`
    - pkg install -y ruby ruby${RB}-gems rubygem-rake git
    - gem install bundler
    - bundle install
  script:
    - ruby --version
    - bundle exec rake spec

Windows_task:
  env:
    matrix:
      - RUBY_VERSION: 2.5.3.101
      - RUBY_VERSION: 2.6.3.1
      - RUBY_VERSION: 2.7.0.1
  windows_container:
    os_version: 2019
    image: cirrusci/windowsservercore:2019
  install_script:
    - choco install -y ruby --version %RUBY_VERSION%
    - refreshenv
    - gem update --system
    - gem install bundler
    - bundle install
  script:
    - refreshenv
    - bundle exec rake spec
