#!/usr/bin/env ruby

# frozen_string_literal: true

require "how_is"
require "how_is/cli"
require "how_is/config"

begin
  cli = HowIs::CLI.parse(ARGV)
rescue OptionParser::ParseError => e
  abort "how_is: error: #{e.message}"
end

options = cli.options

abort cli.help_text         if options[:help]
abort HowIs::VERSION_STRING if options[:version]

date = options[:date]

begin
  config = HowIs::Config.with_defaults

  if options[:config]
    config.load_files(options[:config])
  else
    config.load(HowIs.default_config(options[:repository]))
  end

  reports = HowIs.from_config(config, date)

  files = reports.save_all
  puts "Saved reports to:"
  files.each { |file| puts "- #{file}" }
rescue => e
  raise if options[:verbose]

  warn "how_is: error: #{e.message} (Pass --verbose for more details.)"
  warn "  at: #{e.backtrace_locations.first}"
  exit 1
end
