#!/usr/bin/env ruby

require "how_is"
require "optparse"

options = {
  repository: nil,
  report_file:  "report.pdf",
  from_file: nil,
}

opts = OptionParser.new do |opts|
  opts.banner =
    <<-EOF.gsub(/ *\| ?/, '')
      | Usage: how_is REPOSITORY [--report REPORT_FILE]
      |
      | Where REPOSITORY is of the format <GitHub username or org>/<repository name>.
      |
      | E.g., if you wanted to check https://github.com/duckinator/how_is,
      | you'd run `how_is duckinator/how_is`.
      |
    EOF

  opts.separator ""
  opts.separator "Options:"

  opts.on("-h", "--help", "Print this help") do
    puts opts
    exit 0
  end

  opts.on("--from JSON_REPORT_FILE", "import JSON_REPORT_FILE instead of fetching the data again") do |file|
    options[:from_file] = file
  end

  opts.on("--report REPORT_FILE", "CSV file containing the report") do |file|
    options[:report_file] = file
  end
end
opts.parse!

if options[:from_file]
  # Opening this file here seems a bit messy, but it works.
  options[:repository] = JSON.parse(open(options[:from_file]).read)['repository']
  abort "Error: Invalid JSON report file." unless options[:repository]
elsif ARGV.length >= 1
  options[:repository] = ARGV.delete_at(0)
else
  abort "Error: No repository specified."
end

HowIs.generate_report(options)
